name: 'Run PHPCS with reviewdog'
description: '🐶 Run phpcs with reviewdog on pull requests to improve code review experience.'
author: 'SAU/CAL'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'PHPCS'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-review.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `true`.
    default: 'true'
  level:
    description: 'Report level for reviewdog [info, warning, error]'
    default: 'warning'
runs:
  using: 'docker'
  image: 'Dockerfile'
